#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      if !defined(Py_GIL_DISABLED)
#        define Py_LIMITED_API
#      else
#        define Py_LIMITED_API 0x030f0000
#      endif
#    endif

#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      if !defined(Py_GIL_DISABLED)
#        define Py_LIMITED_API
#      else
#        define Py_LIMITED_API 0x030f0000
#      endif
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>
#include <stdlib.h>
#include <string.h>


/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyLong_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyLong_FromLong((long)x) :                                   \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyLong_FromLong((long)x) :                                   \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


/*
 * Ported from the PixelMed Java JPEG Selective Block Redaction Codec
 * (https://www.pixelmed.com/jpeg.html).
 *
 * Copyright (c) 2001-2025, David A. Clunie DBA PixelMed Publishing.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimers.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimers in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of PixelMed Publishing nor the names of its contributors
 *    may be used to endorse or promote products derived from this software.
 *
 * This software is provided by the copyright holders and contributors "as is"
 * and any express or implied warranties, including, but not limited to, the
 * implied warranties of merchantability and fitness for a particular purpose
 * are disclaimed. In no event shall the copyright owner or contributors be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data or profits; or business
 * interruption) however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this software, even if advised of the
 * possibility of such damage.
 *
 * This software has neither been tested nor approved for clinical use or for
 * incorporation in a medical device. It is the redistributor's or user's
 * responsibility to comply with any applicable local, state, national or
 * international regulations.
 */
#include <stdint.h>
#include <string.h>

/* ---------- Huffman table (decoded from Python-side arrays) ---------- */

typedef struct {
    int mincode[17];
    int maxcode[17];
    int valptr[17];
    int huffval[256];
    int huffval_count;
    int efufco[256];
    int efufsi[256];
    int efuf_len;
    int eob_code;
    int eob_code_length;
} HuffTable;

/* ---------- Bit reader with JPEG byte-stuffing ---------- */

typedef struct {
    const uint8_t *data;
    int len;
    int pos;
    uint32_t bit_buffer;
    int bits_available;
} BitReader;

static inline void br_init(BitReader *br, const uint8_t *data, int len) {
    br->data = data;
    br->len = len;
    br->pos = 0;
    br->bit_buffer = 0;
    br->bits_available = 0;
}

static inline int br_next_byte(BitReader *br) {
    if (br->pos >= br->len) return -1;
    int b = br->data[br->pos++];
    if (b == 0xFF && br->pos < br->len) {
        uint8_t next = br->data[br->pos];
        if (next == 0x00) {
            br->pos++;  /* byte stuffing */
        }
        /* RST markers inside data are handled at MCU boundary level */
    }
    return b;
}

static inline int br_get_bits(BitReader *br, int n) {
    while (br->bits_available < n) {
        int b = br_next_byte(br);
        if (b < 0) return 0;
        br->bit_buffer = (br->bit_buffer << 8) | (uint32_t)b;
        br->bits_available += 8;
    }
    br->bits_available -= n;
    return (int)((br->bit_buffer >> br->bits_available) & ((1u << n) - 1));
}

static inline int br_get_bit(BitReader *br) {
    return br_get_bits(br, 1);
}

/* ---------- Bit writer with JPEG byte-stuffing ---------- */

typedef struct {
    uint8_t *output;
    int capacity;
    int pos;
    int bit_buffer;
    int bits_pending;
} BitWriter;

static inline void bw_init(BitWriter *bw, uint8_t *output, int capacity) {
    bw->output = output;
    bw->capacity = capacity;
    bw->pos = 0;
    bw->bit_buffer = 0;
    bw->bits_pending = 0;
}

static inline void bw_flush_byte(BitWriter *bw) {
    uint8_t b = (uint8_t)(bw->bit_buffer & 0xFF);
    if (bw->pos < bw->capacity) bw->output[bw->pos++] = b;
    if (b == 0xFF && bw->pos < bw->capacity) {
        bw->output[bw->pos++] = 0x00;  /* byte stuffing */
    }
    bw->bit_buffer = 0;
    bw->bits_pending = 0;
}

static inline void bw_write_bits(BitWriter *bw, int value, int n) {
    for (int i = n - 1; i >= 0; --i) {
        bw->bit_buffer = (bw->bit_buffer << 1) | ((value >> i) & 1);
        bw->bits_pending++;
        if (bw->bits_pending == 8) {
            bw_flush_byte(bw);
        }
    }
}

static inline void bw_flush(BitWriter *bw) {
    if (bw->bits_pending > 0) {
        bw->bit_buffer <<= (8 - bw->bits_pending);
        bw->bit_buffer |= (1 << (8 - bw->bits_pending)) - 1;  /* pad with 1s */
        bw->bits_pending = 8;
        bw_flush_byte(bw);
    }
}

/* ---------- Huffman decode/encode ---------- */

static inline int huff_decode(BitReader *br, const HuffTable *ht) {
    int code = 0;
    for (int length = 1; length <= 16; length++) {
        code = (code << 1) | br_get_bit(br);
        if (code <= ht->maxcode[length] && ht->maxcode[length] >= 0) {
            int idx = ht->valptr[length] + code - ht->mincode[length];
            return ht->huffval[idx];
        }
    }
    return 0;  /* invalid code, return 0 as safe fallback */
}

static inline void huff_encode(BitWriter *bw, const HuffTable *ht, int symbol) {
    if (symbol < ht->efuf_len) {
        bw_write_bits(bw, ht->efufco[symbol], ht->efufsi[symbol]);
    }
}

static inline int receive_extend(BitReader *br, int nbits) {
    if (nbits == 0) return 0;
    int value = br_get_bits(br, nbits);
    if (value < (1 << (nbits - 1))) {
        value -= (1 << nbits) - 1;
    }
    return value;
}

static inline void size_and_amplitude(int value, int *size_out, int *amp_out) {
    if (value == 0) {
        *size_out = 0;
        *amp_out = 0;
        return;
    }
    int absval = value < 0 ? -value : value;
    int size = 0;
    int tmp = absval;
    while (tmp > 0) { size++; tmp >>= 1; }
    int amplitude;
    if (value < 0) {
        amplitude = (value - 1) & ((1 << size) - 1);
    } else {
        amplitude = value & ((1 << size) - 1);
    }
    *size_out = size;
    *amp_out = amplitude;
}

/* ---------- Region overlap test ---------- */

static inline int block_overlaps_any_region(
    int bx, int by, int bw, int bh,
    int num_regions, const int *regions)
{
    int bx2 = bx + bw;
    int by2 = by + bh;
    for (int i = 0; i < num_regions; i++) {
        int rx = regions[i * 4];
        int ry = regions[i * 4 + 1];
        int rw = regions[i * 4 + 2];
        int rh = regions[i * 4 + 3];
        if (bx < rx + rw && bx2 > rx && by < ry + rh && by2 > ry) {
            return 1;
        }
    }
    return 0;
}

/* ---------- Main processing function ---------- */

int process_entropy_segment(
    const uint8_t *entropy_data,
    int entropy_len,
    int image_width,
    int image_height,
    int num_components,
    const int *comp_h_sampling,
    const int *comp_v_sampling,
    int num_scan_components,
    const int *scan_dc_table_idx,
    const int *scan_ac_table_idx,
    const int *scan_h_blocks,
    const int *scan_v_blocks,
    /* DC tables: each table has 17 entries for mincode/maxcode/valptr */
    int num_dc_tables,
    const int *dc_table_ids,
    const int *dc_mincode,      /* num_dc_tables * 17 */
    const int *dc_maxcode,      /* num_dc_tables * 17 */
    const int *dc_valptr,       /* num_dc_tables * 17 */
    const int *dc_huffval,      /* flattened, use dc_huffval_counts for offsets */
    const int *dc_huffval_counts,
    const int *dc_efufco,       /* flattened, use dc_efuf_len for sizes */
    const int *dc_efufsi,
    const int *dc_efuf_len,
    /* AC tables */
    int num_ac_tables,
    const int *ac_table_ids,
    const int *ac_mincode,
    const int *ac_maxcode,
    const int *ac_valptr,
    const int *ac_huffval,
    const int *ac_huffval_counts,
    const int *ac_efufco,
    const int *ac_efufsi,
    const int *ac_efuf_len,
    const int *ac_eob_code,
    const int *ac_eob_code_length,
    /* Other params */
    int restart_interval,
    int num_regions,
    const int *regions,
    /* Output */
    uint8_t *output,
    int output_capacity,
    int *output_len)
{
    /* Build local HuffTable structs from flat arrays */
    HuffTable dc_tables[4];
    HuffTable ac_tables[4];
    memset(dc_tables, 0, sizeof(dc_tables));
    memset(ac_tables, 0, sizeof(ac_tables));

    int dc_hv_offset = 0;
    int dc_ef_offset = 0;
    for (int t = 0; t < num_dc_tables && t < 4; t++) {
        int id = dc_table_ids[t];
        if (id < 0 || id > 3) continue;
        HuffTable *ht = &dc_tables[id];
        for (int i = 0; i < 17; i++) {
            ht->mincode[i] = dc_mincode[t * 17 + i];
            ht->maxcode[i] = dc_maxcode[t * 17 + i];
            ht->valptr[i] = dc_valptr[t * 17 + i];
        }
        int hv_count = dc_huffval_counts[t];
        for (int i = 0; i < hv_count && i < 256; i++) {
            ht->huffval[i] = dc_huffval[dc_hv_offset + i];
        }
        ht->huffval_count = hv_count;
        dc_hv_offset += hv_count;

        int ef_len = dc_efuf_len[t];
        for (int i = 0; i < ef_len && i < 256; i++) {
            ht->efufco[i] = dc_efufco[dc_ef_offset + i];
            ht->efufsi[i] = dc_efufsi[dc_ef_offset + i];
        }
        ht->efuf_len = ef_len;
        dc_ef_offset += ef_len;
    }

    int ac_hv_offset = 0;
    int ac_ef_offset = 0;
    for (int t = 0; t < num_ac_tables && t < 4; t++) {
        int id = ac_table_ids[t];
        if (id < 0 || id > 3) continue;
        HuffTable *ht = &ac_tables[id];
        for (int i = 0; i < 17; i++) {
            ht->mincode[i] = ac_mincode[t * 17 + i];
            ht->maxcode[i] = ac_maxcode[t * 17 + i];
            ht->valptr[i] = ac_valptr[t * 17 + i];
        }
        int hv_count = ac_huffval_counts[t];
        for (int i = 0; i < hv_count && i < 256; i++) {
            ht->huffval[i] = ac_huffval[ac_hv_offset + i];
        }
        ht->huffval_count = hv_count;
        ac_hv_offset += hv_count;

        int ef_len = ac_efuf_len[t];
        for (int i = 0; i < ef_len && i < 256; i++) {
            ht->efufco[i] = ac_efufco[ac_ef_offset + i];
            ht->efufsi[i] = ac_efufsi[ac_ef_offset + i];
        }
        ht->efuf_len = ef_len;
        ac_ef_offset += ef_len;

        ht->eob_code = ac_eob_code[t];
        ht->eob_code_length = ac_eob_code_length[t];
    }

    /* Determine MCU layout */
    int max_h = 0, max_v = 0;
    for (int i = 0; i < num_components; i++) {
        if (comp_h_sampling[i] > max_h) max_h = comp_h_sampling[i];
        if (comp_v_sampling[i] > max_v) max_v = comp_v_sampling[i];
    }
    int mcu_width = max_h * 8;
    int mcu_height = max_v * 8;
    int mcus_per_row = (image_width + mcu_width - 1) / mcu_width;
    int mcus_per_col = (image_height + mcu_height - 1) / mcu_height;
    int total_mcus = mcus_per_row * mcus_per_col;

    BitReader reader;
    br_init(&reader, entropy_data, entropy_len);

    BitWriter writer;
    bw_init(&writer, output, output_capacity);

    int orig_prev_dc[4] = {0};
    int out_prev_dc[4] = {0};
    int mcu_count = 0;

    for (int mcu_idx = 0; mcu_idx < total_mcus; mcu_idx++) {
        int mcu_row = mcu_idx / mcus_per_row;
        int mcu_col = mcu_idx % mcus_per_row;

        for (int ci = 0; ci < num_scan_components; ci++) {
            int dc_tid = scan_dc_table_idx[ci];
            int ac_tid = scan_ac_table_idx[ci];
            const HuffTable *dc_ht = &dc_tables[dc_tid];
            const HuffTable *ac_ht = &ac_tables[ac_tid];
            int h_blocks = scan_h_blocks[ci];
            int v_blocks = scan_v_blocks[ci];

            for (int bv = 0; bv < v_blocks; bv++) {
                for (int bh = 0; bh < h_blocks; bh++) {
                    int h_block_size = 8 * max_h / h_blocks;
                    int v_block_size = 8 * max_v / v_blocks;
                    int block_x = mcu_col * mcu_width + bh * h_block_size;
                    int block_y = mcu_row * mcu_height + bv * v_block_size;

                    int should_blank = block_overlaps_any_region(
                        block_x, block_y, h_block_size, v_block_size,
                        num_regions, regions);

                    /* Decode DC */
                    int dc_size = huff_decode(&reader, dc_ht);
                    int dc_diff = receive_extend(&reader, dc_size);
                    int orig_dc_value = orig_prev_dc[ci] + dc_diff;
                    orig_prev_dc[ci] = orig_dc_value;

                    int new_dc_value = should_blank ? 0 : orig_dc_value;
                    int new_dc_diff = new_dc_value - out_prev_dc[ci];
                    out_prev_dc[ci] = new_dc_value;

                    int new_size, new_amp;
                    size_and_amplitude(new_dc_diff, &new_size, &new_amp);
                    huff_encode(&writer, dc_ht, new_size);
                    if (new_size > 0) {
                        bw_write_bits(&writer, new_amp, new_size);
                    }

                    /* Decode and re-encode AC */
                    if (should_blank) {
                        int k = 1;
                        while (k < 64) {
                            int rs = huff_decode(&reader, ac_ht);
                            int rrrr = (rs >> 4) & 0x0F;
                            int ssss = rs & 0x0F;
                            if (ssss == 0) {
                                if (rrrr == 0) break;       /* EOB */
                                if (rrrr == 0x0F) { k += 16; continue; }  /* ZRL */
                            } else {
                                receive_extend(&reader, ssss);  /* discard */
                                k += rrrr + 1;
                            }
                        }
                        /* Write EOB */
                        huff_encode(&writer, ac_ht, 0x00);
                    } else {
                        int k = 1;
                        while (k < 64) {
                            int rs = huff_decode(&reader, ac_ht);
                            int rrrr = (rs >> 4) & 0x0F;
                            int ssss = rs & 0x0F;
                            huff_encode(&writer, ac_ht, rs);
                            if (ssss == 0) {
                                if (rrrr == 0) break;       /* EOB */
                                if (rrrr == 0x0F) { k += 16; continue; }
                            } else {
                                int val = receive_extend(&reader, ssss);
                                int dummy_size, amp;
                                size_and_amplitude(val, &dummy_size, &amp);
                                bw_write_bits(&writer, amp, ssss);
                                k += rrrr + 1;
                            }
                        }
                    }
                }
            }
        }

        mcu_count++;

        /* Handle restart markers */
        if (restart_interval > 0 &&
            mcu_count % restart_interval == 0 &&
            mcu_idx < total_mcus - 1)
        {
            bw_flush(&writer);
            int rst_num = ((mcu_count / restart_interval) - 1) % 8;
            if (writer.pos < writer.capacity) writer.output[writer.pos++] = 0xFF;
            if (writer.pos < writer.capacity) writer.output[writer.pos++] = (uint8_t)(0xD0 + rst_num);

            /* Reset DC predictions */
            for (int ci = 0; ci < num_scan_components; ci++) {
                orig_prev_dc[ci] = 0;
                out_prev_dc[ci] = 0;
            }

            /* Reset reader bit state */
            reader.bits_available = 0;

            /* Skip RST marker in input */
            while (reader.pos < reader.len) {
                if (reader.data[reader.pos] == 0xFF) {
                    if (reader.pos + 1 < reader.len &&
                        reader.data[reader.pos + 1] >= 0xD0 &&
                        reader.data[reader.pos + 1] <= 0xD7)
                    {
                        reader.pos += 2;
                        break;
                    }
                    else if (reader.pos + 1 < reader.len &&
                             reader.data[reader.pos + 1] == 0x00)
                    {
                        break;
                    }
                }
                break;
            }
        }
    }

    bw_flush(&writer);
    *output_len = writer.pos;
    return 0;
}


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 2), // int()(uint8_t const *, int, int, int, int, int const *, int const *, int, int const *, int const *, int const *, int const *, int, int const *, int const *, int const *, int const *, int const *, int const *, int const *, int const *, int const *, int, int const *, int const *, int const *, int const *, int const *, int const *, int const *, int const *, int const *, int const *, int const *, int, int, int const *, uint8_t *, int, int *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // uint8_t const *
/*  2 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  3 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/*  4 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/*  5 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 2), // int const *
/*  7 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/*  8 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/*  9 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 10 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 11 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 12 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 13 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 15 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 16 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 17 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 18 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 19 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 20 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 21 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 23 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 26 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 27 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 28 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 29 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 32 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 33 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 34 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 35 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 36 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 37 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 38 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // uint8_t *
/* 39 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 40 */ _CFFI_OP(_CFFI_OP_POINTER, 2), // int *
/* 41 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
};

static int _cffi_d_process_entropy_segment(uint8_t const * x0, int x1, int x2, int x3, int x4, int const * x5, int const * x6, int x7, int const * x8, int const * x9, int const * x10, int const * x11, int x12, int const * x13, int const * x14, int const * x15, int const * x16, int const * x17, int const * x18, int const * x19, int const * x20, int const * x21, int x22, int const * x23, int const * x24, int const * x25, int const * x26, int const * x27, int const * x28, int const * x29, int const * x30, int const * x31, int const * x32, int const * x33, int x34, int x35, int const * x36, uint8_t * x37, int x38, int * x39)
{
  return process_entropy_segment(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31, x32, x33, x34, x35, x36, x37, x38, x39);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_process_entropy_segment(PyObject *self, PyObject *args)
{
  uint8_t const * x0;
  int x1;
  int x2;
  int x3;
  int x4;
  int const * x5;
  int const * x6;
  int x7;
  int const * x8;
  int const * x9;
  int const * x10;
  int const * x11;
  int x12;
  int const * x13;
  int const * x14;
  int const * x15;
  int const * x16;
  int const * x17;
  int const * x18;
  int const * x19;
  int const * x20;
  int const * x21;
  int x22;
  int const * x23;
  int const * x24;
  int const * x25;
  int const * x26;
  int const * x27;
  int const * x28;
  int const * x29;
  int const * x30;
  int const * x31;
  int const * x32;
  int const * x33;
  int x34;
  int x35;
  int const * x36;
  uint8_t * x37;
  int x38;
  int * x39;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;
  PyObject *arg9;
  PyObject *arg10;
  PyObject *arg11;
  PyObject *arg12;
  PyObject *arg13;
  PyObject *arg14;
  PyObject *arg15;
  PyObject *arg16;
  PyObject *arg17;
  PyObject *arg18;
  PyObject *arg19;
  PyObject *arg20;
  PyObject *arg21;
  PyObject *arg22;
  PyObject *arg23;
  PyObject *arg24;
  PyObject *arg25;
  PyObject *arg26;
  PyObject *arg27;
  PyObject *arg28;
  PyObject *arg29;
  PyObject *arg30;
  PyObject *arg31;
  PyObject *arg32;
  PyObject *arg33;
  PyObject *arg34;
  PyObject *arg35;
  PyObject *arg36;
  PyObject *arg37;
  PyObject *arg38;
  PyObject *arg39;

  if (!PyArg_UnpackTuple(args, "process_entropy_segment", 40, 40, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8, &arg9, &arg10, &arg11, &arg12, &arg13, &arg14, &arg15, &arg16, &arg17, &arg18, &arg19, &arg20, &arg21, &arg22, &arg23, &arg24, &arg25, &arg26, &arg27, &arg28, &arg29, &arg30, &arg31, &arg32, &arg33, &arg34, &arg35, &arg36, &arg37, &arg38, &arg39))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (uint8_t const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, int);
  if (x3 == (int)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, int);
  if (x4 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg5, (char **)&x5);
  if (datasize != 0) {
    x5 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg5, (char **)&x5,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg6, (char **)&x6);
  if (datasize != 0) {
    x6 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg6, (char **)&x6,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x7 = _cffi_to_c_int(arg7, int);
  if (x7 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg8, (char **)&x8);
  if (datasize != 0) {
    x8 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg8, (char **)&x8,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg9, (char **)&x9);
  if (datasize != 0) {
    x9 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg9, (char **)&x9,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg10, (char **)&x10);
  if (datasize != 0) {
    x10 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg10, (char **)&x10,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg11, (char **)&x11);
  if (datasize != 0) {
    x11 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg11, (char **)&x11,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x12 = _cffi_to_c_int(arg12, int);
  if (x12 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg13, (char **)&x13);
  if (datasize != 0) {
    x13 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg13, (char **)&x13,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg14, (char **)&x14);
  if (datasize != 0) {
    x14 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg14, (char **)&x14,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg15, (char **)&x15);
  if (datasize != 0) {
    x15 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg15, (char **)&x15,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg16, (char **)&x16);
  if (datasize != 0) {
    x16 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg16, (char **)&x16,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg17, (char **)&x17);
  if (datasize != 0) {
    x17 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg17, (char **)&x17,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg18, (char **)&x18);
  if (datasize != 0) {
    x18 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg18, (char **)&x18,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg19, (char **)&x19);
  if (datasize != 0) {
    x19 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg19, (char **)&x19,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg20, (char **)&x20);
  if (datasize != 0) {
    x20 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg20, (char **)&x20,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg21, (char **)&x21);
  if (datasize != 0) {
    x21 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg21, (char **)&x21,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x22 = _cffi_to_c_int(arg22, int);
  if (x22 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg23, (char **)&x23);
  if (datasize != 0) {
    x23 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg23, (char **)&x23,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg24, (char **)&x24);
  if (datasize != 0) {
    x24 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg24, (char **)&x24,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg25, (char **)&x25);
  if (datasize != 0) {
    x25 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg25, (char **)&x25,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg26, (char **)&x26);
  if (datasize != 0) {
    x26 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg26, (char **)&x26,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg27, (char **)&x27);
  if (datasize != 0) {
    x27 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg27, (char **)&x27,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg28, (char **)&x28);
  if (datasize != 0) {
    x28 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg28, (char **)&x28,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg29, (char **)&x29);
  if (datasize != 0) {
    x29 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg29, (char **)&x29,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg30, (char **)&x30);
  if (datasize != 0) {
    x30 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg30, (char **)&x30,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg31, (char **)&x31);
  if (datasize != 0) {
    x31 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg31, (char **)&x31,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg32, (char **)&x32);
  if (datasize != 0) {
    x32 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg32, (char **)&x32,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg33, (char **)&x33);
  if (datasize != 0) {
    x33 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg33, (char **)&x33,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x34 = _cffi_to_c_int(arg34, int);
  if (x34 == (int)-1 && PyErr_Occurred())
    return NULL;

  x35 = _cffi_to_c_int(arg35, int);
  if (x35 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg36, (char **)&x36);
  if (datasize != 0) {
    x36 = ((size_t)datasize) <= 640 ? (int const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg36, (char **)&x36,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(38), arg37, (char **)&x37);
  if (datasize != 0) {
    x37 = ((size_t)datasize) <= 640 ? (uint8_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(38), arg37, (char **)&x37,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x38 = _cffi_to_c_int(arg38, int);
  if (x38 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(40), arg39, (char **)&x39);
  if (datasize != 0) {
    x39 = ((size_t)datasize) <= 640 ? (int *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(40), arg39, (char **)&x39,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = process_entropy_segment(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31, x32, x33, x34, x35, x36, x37, x38, x39); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_process_entropy_segment _cffi_d_process_entropy_segment
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "process_entropy_segment", (void *)_cffi_f_process_entropy_segment, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_process_entropy_segment },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  1,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  43,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__jpeg_dct_accel(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
    return NULL;
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
     PyInit__jpeg_dct_accel(void) { return NULL; }
#  endif
#else
PyMODINIT_FUNC
PyInit__jpeg_dct_accel(void)
{
  return _cffi_init("dicom_dre._jpeg_dct_accel", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
